Repository Fermin-Cardenas/dabetai-mobileapp, pull requests merged in 2025-07, with the labels that each got.

#3 docs: add pull request template to speed up process
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#2 docs: add contributing guidelines with clear workflow and conventions
  CONTRIBUTING.MD
Labels: documentation

#9 feat: update gitignore to include api files
  .gitignore
Labels: enhancement

#10 feat: improve dashboard chart logic and UI design
  app/(tabs)/home.tsx
  app/(tabs)/prediction/index.tsx
  package-lock.json
  package.json
  src/features/dashboard/components/RecordChart.tsx
  src/features/dashboard/components/RiskLevelCard.tsx
  src/features/dashboard/components/TrendChart.tsx
Labels: enhancement

#6 docs: restructure and enhance project README
  README.md
  assets/screenshots/chat.png
  assets/screenshots/dashboard.png
  assets/screenshots/login.png
  assets/screenshots/predictions.png
Labels: documentation, enhancement
